### ISSUE TITLE
main.c is empty

### ISSUE THREAD

**Issue by obiwan45** [damonearp/teensy-3.2-msd#1]
main.c is empty

NOT WORKING

**Comment by damonearp** [comment]
You are correct, `main.c` spins wheels and does nothing. Everything happens through the [usb_dev.c](https://github.com/damonearp/teensy-3.2-msd/blob/master/src/usb_dev.c), specifically line [231](https://github.com/damonearp/teensy-3.2-msd/blob/master/src/usb_dev.c#L231). 

Basically when the hex file is loaded into the teensy it has a init routine that runs before `main()` which enables the USB chip and registers handlers for the different USB endpoints. Endpoint 0 is required for discovery and control, then endpoint 1 and 2 are enabled by defining the symbols `usb_ep1_handler` and `usb_ep2_handler` in [usb_msd.c](https://github.com/damonearp/teensy-3.2-msd/blob/master/src/usb_msd.c#L109). The chip will then call the code whenever a USB event happens. 

In effect `main.c` can probably be deleted completely, I don't even know if it is ever called. I started by following [teensy-cores](https://github.com/PaulStoffregen/cores) which is tied into Arduino and slowly removed everything so I would just have a mass storage device. 

It has only been tested on a [Teensy 3.2](https://www.pjrc.com/store/teensy32.html) with the [Micro-SD Adapter](https://www.pjrc.com/store/wiz820_sd_adaptor.html). If the SD adapter is missing and no card is detected, I believe it will sit idly by and not do anything since there is no storage to manage.

If you want to diagnose what's going on it will log to the hardware serial1, aka TX on pin 1 (default baud of 115200).  

Enjoy!
